### ISSUE TITLE
Unable to add flags/options via docker container

### ISSUE THREAD

**Issue by guppie70** [willemvlh/saxon-server#15]
I use the following definition for adding the service to one of my stacks:
```
xsltservice:
    image: ghcr.io/willemvlh/saxon-server:latest
    environment:
      # - JAVA_OPTS="-Xmx1g"
    ports:
      - 8091:5000/tcp
```
When I enable the JAVA_OPTS line in the container definition it ends up in a contant restart state with the following log messages:
```
2024-08-20 17:07:40 Error: Could not find or load main class "-Xmx1g"
2024-08-20 17:07:40 Caused by: java.lang.ClassNotFoundException: "-Xmx1g"
```
I am also looking for a way to add the -i or --insecure flag to the java application so that I can run external functions calls. How can I achieve that?

**Comment by willemvlh** [comment]
Hi,
I've released a new version (2.6) in which this should be fixed. Something like this should work:

```
services:
  xslt:
    image: ghcr.io/willemvlh/saxon-server:latest
    command: --insecure
    ports:
      - 5000:5000
    environment:
      JAVA_OPTS: "-Xmx1g"
```
